### ISSUE TITLE
'Trying to get property of non-object' Hatasi

### ISSUE THREAD

**Issue by kaanklky** [salyangoz/pazaryeri-parasut#1]
Merhaba, kodu denemeye calistigimda asagidaki ciktiyi aliyorum. Sorunun nereden kaynaklandigini anlayamadim.

```
php artisan pazaryeriparasut:transfer -vvv

                                                           
  [Exception]                                              
  Trying to get property of non-object
                                                           

Exception trace:
 () at vendor/salyangoz/pazaryeri-parasut/src/Marketplace/N11.php:56
 Illuminate\Foundation\Bootstrap\HandleExceptions->handleError() at vendor/salyangoz/pazaryeri-parasut/src/Marketplace/N11.php:56
 salyangoz\pazaryeriparasut\Marketplace\N11->sales() at vendor/salyangoz/pazaryeri-parasut/src/Marketplace/N11.php:75
 salyangoz\pazaryeriparasut\Marketplace\N11->transfer() at vendor/salyangoz/pazaryeri-parasut/src/Client.php:25
 salyangoz\pazaryeriparasut\Client->transfer() at vendor/salyangoz/pazaryeri-parasut/src/Commands/Transfer.php:43
 salyangoz\pazaryeriparasut\Commands\Transfer->handle() at n/a:n/a
 call_user_func_array() at vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:29
 Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() at vendor/mayoz/parasut/src/helpers.php:87
 value() at vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:86
 Illuminate\Container\BoundMethod::callBoundMethod() at vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:30
 Illuminate\Container\BoundMethod::call() at vendor/laravel/framework/src/Illuminate/Container/Container.php:524
 Illuminate\Container\Container->call() at vendor/laravel/framework/src/Illuminate/Console/Command.php:182
 Illuminate\Console\Command->execute() at vendor/symfony/console/Command/Command.php:262
 Symfony\Component\Console\Command\Command->run() at vendor/laravel/framework/src/Illuminate/Console/Command.php:168
 Illuminate\Console\Command->run() at vendor/symfony/console/Application.php:826
 Symfony\Component\Console\Application->doRunCommand() at vendor/symfony/console/Application.php:189
 Symfony\Component\Console\Application->doRun() at vendor/symfony/console/Application.php:120
 Symfony\Component\Console\Application->run() at vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:123
 Illuminate\Foundation\Console\Kernel->handle() at artisan:36
```

**Comment by yedincisenol** [comment]
@kaanklky Sorun n11'in istek limitinden kaynaklanıyor. Şurdaki gibi sleep time'ın 7 olduğundan emin olmanız gererekiyo. Ya da o süreyi artırmak gerekiyor. 

https://github.com/salyangoz/pazaryeri-parasut/blob/master/src/Marketplace/N11.php#L100

Ardarda menuel istek yapıldığında da bu hata alınabiliyor, o yüzden istek sayısını 10dkda bir yapmak da daha stabil çalışma sağlar.

Ayrıca projenin yeni versiyonunu composer'a atmadık. Dolayısıyla githubdaki son repo ile, composerdaki farklı.

**Comment by kaanklky** [comment]
@yedincisenol Tesekkurler, dediginiz gibi; composer uzerinden kurdugum icin sleep komutu bile yoktu ancak foreach dongusunden sonra sleep(10) ekleyince calisti. 

Musadenizle birkac sorum daha olacak:
- Parasut'te kategori olusturuyorum ancak sistem bana kategori id'sini vermiyor, o yuzden cektigim faturalar kategoriye eklenmiyor. Parasut'te kategori id'sini nasil bulabilirim?
- N11'de gelen siparis kurumsal olabiliyor ve sipariste Firma Adi bulunmasina ragmen Parasut'e firma adi olarak bireysel isim dusuyor. Bunu halletmenin bir yolu var mi yoksa N11 API'si uzerinden firma ismini kontrol ettirip varsa onu yazdirma kismini kendim mi yazmaliyim?
- Composer'a yeni surumu ne zaman yuklersiniz? :) Yol haritaniz belli mi?
