### ISSUE TITLE
Parasut\Exception\UnauthorizedException  : Unauthorized

### ISSUE THREAD

**Issue by mfadel85** [salyangoz/pazaryeri-parasut#3]
Teşekkürler,
$php artisan pazaryeriparasut:transfer 
uyguladıtktan sonra, ekranda bu 
çıktı
vendor/mayoz/parasut/src/Client.php:287
 curl_close($ch);

```
switch ($httpCode) {
case '401':
```

> throw new UnauthorizedException;
 break;
 case '404':
 throw new NotFoundException;
 break;

Exception trace:

1 Parasut\Client::send("https://api.parasut.com/oauth/token", "POST")
 /*******/vendor/mayoz/parasut/src/Client.php:123

2 Parasut\Client::authorize()
 /*******//vendor/salyangoz/pazaryeri-parasut/src/Marketplace/Marketplace.php:30

Please use the argument -v to see more details.

.env dosyasında 
bunları ayarladım:
PARASUT_CLIENT_ID=****
PARASUT_CLIENT_SECRET=*******
PARASUT_USERNAME=*******
PARASUT_COMPANY_ID=*****
PARASUT_PASSWORD=*****
PARASUT_CATEGORY_ID=****
PARASUT_ACCOUNT_ID=*****

N11_APP_KEY=*****
N11_APP_SECRET=******

bu problem nasıl çözebilirim?

**Comment by yedincisenol** [comment]
@mfadel85 Kullanıcı giriş bilgilerinde ya da Paraşüt API bilgilerinizde hata olduğunda bu durum oluşur

**Comment by mfadel85** [comment]
@yedincisenol  teşşekürler, hata vardı bilgilerinde,
